os: osx
osx_image: xcode10.1
language: swift
xcode_workspace: Cashlog.xcodeproj
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone XS
xcode_scheme: Cashlog

after_success:
- bash <(curl -s https://codecov.io/bash)
